name: Split Tests
author: martin.tarjanyi@instructure.com
description: Splits test suite for parallelization with equal time
inputs:
  total-sets:
    description: Total number of groups to split the tests into (integer)
    required: true
  current-set:
    description: Index of the current group starting from 0 (integer)
    required: true
  test-files-glob:
    description: Glob pattern to find test files (string)
    required: true
  junit-report-glob:
    description: Glob pattern to JUnit XML reports to use for test timings (string)
    required: true
  prefix:
    description: Enables to specify a prefix to align naming of the test files with the name in the JUnit report (string)
    required: true
    default: ""
  postfix:
    description: Enables to specify a postfix to align naming of the test files with the name in the JUnit report (string)
    required: true
    default: ""
outputs:
  test-suite:
    description: "A subset of test files, based on the the split index"
    value: ${{ steps.split-tests.outputs.test-suite }}
runs:
  using: composite
  steps:
    - name: Download Split Tests
      shell: bash
      run: |
        gh release download v0.5 --repo CanvasCredentials/split-tests
        gunzip split_tests.linux.gz -v > split_tests && chmod +x split_tests
    - name: Split Tests
      id: split-tests
      shell: bash
      run: |
        TESTS=$(./split_tests \
          -junit-path="${{ inputs.junit-report-glob }}" \
          -split-index=${{ inputs.current-set }} \
          -split-total="${{ inputs.total-sets }}" \
          -glob="${{ inputs.test-files-glob }}" \
          -prefix="${{ inputs.prefix }}" \
          -postfix="${{ inputs.postfix }}" \
        )
        echo "test-suite=${TESTS}" >> $GITHUB_OUTPUT
